import express from "express";
import cors from "cors";
import cookieParser from "cookie-parser";
import { env } from "./config/env.js";
import { swaggerHandler, swaggerMiddleware } from "./docs/swagger.js";
import { openapiSpec } from "./docs/openapi.js";
import { authenticationMiddleware } from "./modules/authentication/auth.middleware.js";
import { permissionsMiddleware } from "./modules/permissions/permission.middleware.js";
import { authorizationMiddleware } from "./shared/middleware/authorization.middleware.js";
import { authRouter } from "./modules/authentication/auth.routes.js";
import { usersRouter } from "./modules/users/user.routes.js";
import { permissionsRouter } from "./modules/permissions/permission.routes.js";
import { rolesRouter } from "./modules/roles/role.routes.js";
import { ordersRouter } from "./modules/orders/order.routes.js";
import { messagesRouter } from "./modules/messages/message.routes.js";
import { productsRouter } from "./modules/products/product.routes.js";
import { productCategoriesRouter } from "./modules/product-categories/productCategory.routes.js";
import { testimonialsRouter } from "./modules/testimonials/testimonial.routes.js";
import { bannersRouter } from "./modules/banners/banner.routes.js";
import { healthRouter } from "./modules/health/health.routes.js";
import "./shared/types/express.js";

export const app = express();

app.use(cors({ origin: env.corsOrigin, credentials: true }));
app.use(express.json({ limit: "1mb" }));
app.use(cookieParser());
app.use(authenticationMiddleware);
app.use(permissionsMiddleware);
app.use(authorizationMiddleware);

app.get("/", (_req, res) => res.json({ ok: true, service: "house-of-bread-backend" }));
app.get("/openapi.json", (_req, res) => res.json(openapiSpec));
app.get("/docs/swagger.json", (_req, res) => res.json(openapiSpec));
app.use("/docs", swaggerMiddleware, swaggerHandler);
app.use("/health", healthRouter);
app.use("/api/products", productsRouter);
app.use("/api/product-categories", productCategoriesRouter);
app.use("/api/testimonials", testimonialsRouter);
app.use("/api/banners", bannersRouter);
app.use("/api/messages", messagesRouter);
app.use("/api/orders", ordersRouter);
app.use("/api/auth", authRouter);
app.use("/api/users", usersRouter);
app.use("/api/roles", rolesRouter);
app.use("/api/permissions", permissionsRouter);
